<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Виджет "LightGallery"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Виджет использует лёгкий, модульный скрипт JavaScript для создания лайтбокс-галереи изображений и видео.</p>
    <p>Сайт: <a target="_blank" href="https://www.lightgalleryjs.com">https://www.lightgalleryjs.com</a></p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Настройка виджета "LightGallery"</a></li>
    </ul>
</article>