<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Widget "LightGallery"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>The widget uses lightweight, modular JavaScript to create a lightbox gallery of images and videos.</p>
    <p>Website: <a target="_blank" href="https://www.lightgalleryjs.com">https://www.lightgalleryjs.com</a></p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Customizing widget "LightGallery"</a></li>
    </ul>
</article>